Rscript WrapperCibersort.R ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/Cibersort_Ascites_BluePrintV1.tsv
Rscript WrapperCibersort.R ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/Cibersort_Ascites_ENCODEV2.tsv
Rscript WrapperCibersort.R ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/Cibersort_Ascites_ImmunoStates.tsv
Rscript WrapperCibersort.R ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/Cibersort_Ascites_LM22.tsv
Rscript WrapperCibersort.R ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/Cibersort_CellMixtures_BluePrintV1.tsv
Rscript WrapperCibersort.R ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/Cibersort_CellMixtures_ENCODEV2.tsv
Rscript WrapperCibersort.R ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/Cibersort_CellMixtures_ImmunoStates.tsv
Rscript WrapperCibersort.R ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/Cibersort_CellMixtures_LM22.tsv
Rscript WrapperCibersort.R ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/Cibersort_Hoek_BluePrintV1.tsv
Rscript WrapperCibersort.R ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/Cibersort_Hoek_ENCODEV2.tsv
Rscript WrapperCibersort.R ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/Cibersort_Hoek_ImmunoStates.tsv
Rscript WrapperCibersort.R ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/Cibersort_Hoek_LM22.tsv
