./WrapperDtangle.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/dtangle_Ascites_BluePrintV1.tsv
./WrapperDtangle.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/dtangle_Ascites_ENCODEV2.tsv
./WrapperDtangle.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/dtangle_Ascites_ImmunoStates.tsv
./WrapperDtangle.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/dtangle_Ascites_LM22.tsv
./WrapperDtangle.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/dtangle_CellMixtures_BluePrintV1.tsv
./WrapperDtangle.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/dtangle_CellMixtures_ENCODEV2.tsv
./WrapperDtangle.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/dtangle_CellMixtures_ImmunoStates.tsv
./WrapperDtangle.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/dtangle_CellMixtures_LM22.tsv
./WrapperDtangle.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/dtangle_Hoek_BluePrintV1.tsv
./WrapperDtangle.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/dtangle_Hoek_ENCODEV2.tsv
./WrapperDtangle.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/dtangle_Hoek_ImmunoStates.tsv
./WrapperDtangle.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/dtangle_Hoek_LM22.tsv
