./WrapperDecon.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/Decon_Ascites_BluePrintV1.tsv
./WrapperDecon.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/Decon_Ascites_ENCODEV2.tsv
./WrapperDecon.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/Decon_Ascites_ImmunoStates.tsv
./WrapperDecon.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/Decon_Ascites_LM22.tsv
./WrapperDecon.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/Decon_CellMixtures_BluePrintV1.tsv
./WrapperDecon.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/Decon_CellMixtures_ENCODEV2.tsv
./WrapperDecon.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/Decon_CellMixtures_ImmunoStates.tsv
./WrapperDecon.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/Decon_CellMixtures_LM22.tsv
./WrapperDecon.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/Decon_Hoek_BluePrintV1.tsv
./WrapperDecon.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/Decon_Hoek_ENCODEV2.tsv
./WrapperDecon.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/Decon_Hoek_ImmunoStates.tsv
./WrapperDecon.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/Decon_Hoek_LM22.tsv
