./WrapperGEDIT.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/GEDIT_Ascites_BluePrintV1.tsv
./WrapperGEDIT.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/GEDIT_Ascites_ENCODEV2.tsv
./WrapperGEDIT.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/GEDIT_Ascites_ImmunoStates.tsv
./WrapperGEDIT.sh ../../Inputs/Mixes/Ascites.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/GEDIT_Ascites_LM22.tsv
./WrapperGEDIT.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/GEDIT_CellMixtures_BluePrintV1.tsv
./WrapperGEDIT.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/GEDIT_CellMixtures_ENCODEV2.tsv
./WrapperGEDIT.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/GEDIT_CellMixtures_ImmunoStates.tsv
./WrapperGEDIT.sh ../../Inputs/Mixes/CellMixtures.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/GEDIT_CellMixtures_LM22.tsv
./WrapperGEDIT.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/BluePrintV1.0.tsv ../../Outputs/GEDIT_Hoek_BluePrintV1.tsv
./WrapperGEDIT.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/ENCODEV2.0.tsv ../../Outputs/GEDIT_Hoek_ENCODEV2.tsv
./WrapperGEDIT.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/ImmunoStates.tsv ../../Outputs/GEDIT_Hoek_ImmunoStates.tsv
./WrapperGEDIT.sh ../../Inputs/Mixes/Hoek.tsv ../../Inputs/RefMats/LM22.tsv ../../Outputs/GEDIT_Hoek_LM22.tsv
